### ISSUE TITLE
Why softmax is applied in the _local_layer function?

### ISSUE THREAD

**Issue by XinyiZ001** [RandolphVI/Hierarchical-Multi-Label-Text-Classification#10]
https://github.com/RandolphVI/Hierarchical-Multi-Label-Text-Classification/blob/843aeaa6f7c17937fc137cef02b4d0191dfb35bc/HARNN/text_harnn.py#L101-L103

May I ask why softmax is applied here? Based on my understanding from your paper, the calculated 'score' should directly be multiplied with 'W_att^h' and then average(mean) is applied to generate 'visual' for the next layer.
But from your code, additional softmax is applied before average(mean).

May I ask why softmax is applied here and please correct me if my understanding is wrong and thanks!

**Comment by RandolphVI** [comment]
@XinyiZ001 

Sorry for my mistakes. I used the `score` directly in the paper. 

And I guess is that when I try to verify adding the softmax or not would benefit the final performance  (the effect is basically the same). And the code uploaded is my local version (which is added the `softmax` function) rather than the code version in my server, so there was a deviation.

To summarize, the details you mentioned are my mistakes, but should not affect the use of the model (because the results are basically the same). Also, thank you for your attention to my work.
