### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by akshayparakh25** [RandolphVI/Hierarchical-Multi-Label-Text-Classification#7]
I tried to run the code,
`python train_harnn.py`
And got the following error:

```
☛ Train or Restore?(T/R): t
Traceback (most recent call last):
  File "train_harnn.py", line 80, in <module>
    for attr in sorted(FLAGS.__dict__['__wrapped'])], dilim]))
  File "train_harnn.py", line 80, in <listcomp>
    for attr in sorted(FLAGS.__dict__['__wrapped'])], dilim]))
TypeError: unsupported format string passed to NoneType.__format__

```

Does the code need any command-line arguments?
What could be the possible reason for this error?

**Comment by RandolphVI** [comment]
@akshayparakh25 

Sorry for replying so late.

```python
TRAIN_OR_RESTORE = input("☛ Train or Restore?(T/R): ")

while not (TRAIN_OR_RESTORE.isalpha() and TRAIN_OR_RESTORE.upper() in ['T', 'R']):
    TRAIN_OR_RESTORE = input("✘ The format of your input is illegal, please re-input: ")
logging.info("✔︎ The format of your input is legal, now loading to next step...")
```

The strings (☛, ✘, ✔︎) can be displayed correctly on **MacOS**, but not on **Windows**. (Since I was told earlier that someone uses these strings on **Windows** and causes errors)

So if you are using **Windows**, you can delete these strings and check it again.
